# Generated by Django 5.2.4 on 2025-07-06 20:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titre', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('lieu', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('organisateur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_invite', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('statut', models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé'), ('en_attente', 'En attente')], default='en_attente', max_length=10)),
                ('lien', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('date_reponse', models.DateTimeField(blank=True, null=True)),
                ('evenement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.evenement')),
            ],
        ),
    ]
