# Generated by Django 5.2.4 on 2025-07-12 21:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evenement',
            name='image_evenement',
            field=models.ImageField(blank=True, null=True, upload_to='evenements/'),
        ),
        migrations.AddField(
            model_name='evenement',
            name='style_invitation',
            field=models.CharField(choices=[('moderne', 'Moderne'), ('classique', 'Classique'), ('festif', 'Festif')], default='moderne', max_length=20),
        ),
    ]
