# Generated by Django 5.2.4 on 2025-07-12 21:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evenement_image_evenement_evenement_style_invitation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='evenement',
            name='image_evenement',
            field=models.ImageField(blank=True, help_text="Image d'illustration de l’événement.", null=True, upload_to='evenements/images/'),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='style_invitation',
            field=models.CharField(choices=[('classique', 'Classique'), ('moderne', 'Moderne'), ('élégant', 'Élégant')], default='moderne', help_text="Style visuel prédéfini pour l'invitation.", max_length=20),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='date_reponse',
            field=models.DateTimeField(blank=True, help_text="Date de réponse de l'invité (si disponible).", null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='evenement',
            field=models.ForeignKey(help_text='Événement auquel cette invitation est liée.', on_delete=django.db.models.deletion.CASCADE, related_name='invitations', to='core.evenement'),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='lien',
            field=models.UUIDField(default=uuid.uuid4, editable=False, help_text='Lien unique pour chaque invitation.', unique=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='statut',
            field=models.CharField(choices=[('accepte', 'Accepté'), ('refuse', 'Refusé'), ('en_attente', 'En attente')], default='en_attente', help_text="Statut de la réponse de l'invité.", max_length=10),
        ),
    ]
