# Generated by Django 5.2.3 on 2025-08-04 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_evenement_image_evenement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invitation',
            name='numero_telephone',
            field=models.IntegerField(blank=True, help_text="Numéro de téléphone de l'invité.", max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='evenement',
            name='image_evenement',
            field=models.ImageField(blank=True, help_text="Image d'illustration de l’événement.", null=True, upload_to='evenements/'),
        ),
    ]
